server:
  port: 8080

spring:
  datasource:
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/minimall?characterEncoding=UTF8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      minIdle: 5
      validationQuery: SELECT 1 FROM DUAL
      useGlobalDataSourceStat: true
      initialSize: 5
      maxWait: 60000
      filters: stat,wall,log4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testOnReturn: false
      maxActive: 20
      web-stat-filter: # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        session-stat-enable: false
        principal-cookie-name: admin
        url-pattern: /*
        session-stat-max-count: 1000
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
        enabled: true
        principal-session-name: admin
      stat-view-servlet: # 用途1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*
        login-password: druid!QAZ@WSX
        reset-enable: true
        login-username: droolAdmin
        allow:
        deny:
  redis:
    database: 0
    password: test123
    jedis:
      pool:
        max-idle: 15 # 连接池中的最大空闲连接
        min-idle: 0
        max-active: 50  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 5s
    host: 127.0.0.1
    port: 6379

